# NUMPY

In [2]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4], [5,6,7,8]])

2


# shape of array

In [3]:
print('The shape of the array a is ', a.shape)
print('The shape of the array b is ', b.shape)

The shape of the array a is  (4,)
The shape of the array b is  (2, 4)


# Dimensions

In [4]:
print('The dimensions of array a is ', a.ndim)
print('The dimensions of array b is ', b.ndim)

The dimensions of array a is  1
The dimensions of array b is  2


# Size

In [5]:
print('The size of the array a is ', a.size)
print('The size of the array b is ', b.size)

The size of the array a is  4
The size of the array b is  8


# Datatype

In [6]:
print('The datatype of the array a is ', a.dtype)
print('The datatype of the array b is ', b.dtype)

The datatype of the array a is  int32
The datatype of the array b is  int32


# Itemsize

In [7]:
print('The number of bytes in each element of the array a is  ', a.itemsize)
print('The number of bytes in each element of the array b is ', b.itemsize)

The number of bytes in each element of the array a is   4
The number of bytes in each element of the array b is  4


# arange

In [9]:
array = np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


# reshaping

In [10]:
reshaped = array.reshape(5,2)
print(reshaped)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# np.empty()
Creates an uninitialized (arbitrary) array of specified shape and dtype

In [11]:
np.empty((3,4),dtype='int8')

array([[-96, -69,  85,  92],
       [-36,   2,   0,   0],
       [  0,   0,   0,   0]], dtype=int8)

# np.zeros()
Creates a new array of specified size, filled with zeros

In [12]:
np.zeros((3,4),dtype='int8')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

# np.ones()
Creates a new array of specified size and type, filled with ones

In [13]:
np.ones((3,4),dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

# np.full()
Creates a new array of given shape and type, filled with a constant value

In [14]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

# np.eye()
Creates a 2-D array with ones on the diagonal and zeros elsewhere

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Converting a list to array

In [16]:
#python list
a=[1,2,3]
#convert to NumPy array
b=np.asarray(a)
print(b)

[1 2 3]


# Converting tuples into array

In [18]:
#python tuples
a=((1,2),(3,4))

#convery to NumPy array
b=np.asarray(a)
print(b)

[[1 2]
 [3 4]]


# np.fromiter( )
This function creates a NumPy ndarray from an iterable

In [19]:
a=np.fromiter([1,2,3,4],dtype='int8')
b=np.fromiter((1,2,3,4),dtype='int8')
c=np.fromiter(range(1,5),dtype='int8')
d=np.fromiter('string',dtype='S50')

print("Array a is ",a)
print("Array b is ",b)
print("Array c is ",c)
print("Array d is ",d)

Array a is  [1 2 3 4]
Array b is  [1 2 3 4]
Array c is  [1 2 3 4]
Array d is  [b's' b't' b'r' b'i' b'n' b'g']


# np.arange( )
It returns an array containing evenly spaced values within a given range

Syntax :numpy.arange(start, stop, step, dtype)

Here, numbers are created in the range of [start, stop-1]. We can also specify steps and data type using the step and dtype hyperparameters.

In [20]:
# NumPy array from 1 to 19
print(np.arange(1,20,dtype='int32'))

# NumPy array from 1 to 19 with step size 2
print(np.arange(1,20,2,dtype='int8'))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


# np.linspace( )
It also returns an array within a range but not according to the step size as in the case of .arange() but according to the number of values we want within that range.

Syntax: numpy.linspace(start, stop, num, endpoint, retstep, dtype)

Here, start and stop means the same as in .arange( ) but the difference lies in num, which gives us the number of equally spaced numbers you want to insert within the range [start, stop-1]. The endpoint argument generally is by default set to the stop value (try changing it for some interesting results)

In [21]:
print(np.linspace(1,20,100))

[ 1.          1.19191919  1.38383838  1.57575758  1.76767677  1.95959596
  2.15151515  2.34343434  2.53535354  2.72727273  2.91919192  3.11111111
  3.3030303   3.49494949  3.68686869  3.87878788  4.07070707  4.26262626
  4.45454545  4.64646465  4.83838384  5.03030303  5.22222222  5.41414141
  5.60606061  5.7979798   5.98989899  6.18181818  6.37373737  6.56565657
  6.75757576  6.94949495  7.14141414  7.33333333  7.52525253  7.71717172
  7.90909091  8.1010101   8.29292929  8.48484848  8.67676768  8.86868687
  9.06060606  9.25252525  9.44444444  9.63636364  9.82828283 10.02020202
 10.21212121 10.4040404  10.5959596  10.78787879 10.97979798 11.17171717
 11.36363636 11.55555556 11.74747475 11.93939394 12.13131313 12.32323232
 12.51515152 12.70707071 12.8989899  13.09090909 13.28282828 13.47474747
 13.66666667 13.85858586 14.05050505 14.24242424 14.43434343 14.62626263
 14.81818182 15.01010101 15.2020202  15.39393939 15.58585859 15.77777778
 15.96969697 16.16161616 16.35353535 16.54545455 16

# np.logspace( )
This function returns an array containing numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

Syntax: numpy.logspace(start, stop, num, endpoint, base, dtype)

In [22]:
print(np.logspace(0,2,100))

[  1.           1.04761575   1.09749877   1.149757     1.20450354
   1.26185688   1.32194115   1.38488637   1.45082878   1.51991108
   1.59228279   1.66810054   1.7475284    1.83073828   1.91791026
   2.009233     2.10490414   2.20513074   2.3101297    2.42012826
   2.53536449   2.65608778   2.7825594    2.91505306   3.05385551
   3.19926714   3.35160265   3.51119173   3.67837977   3.85352859
   4.03701726   4.22924287   4.43062146   4.64158883   4.86260158
   5.09413801   5.33669923   5.59081018   5.85702082   6.13590727
   6.42807312   6.73415066   7.05480231   7.39072203   7.74263683
   8.11130831   8.49753436   8.90215085   9.32603347   9.77009957
  10.23531022  10.72267222  11.23324033  11.76811952  12.32846739
  12.91549665  13.53047775  14.17474163  14.84968262  15.55676144
  16.29750835  17.07352647  17.88649529  18.73817423  19.6304065
  20.56512308  21.5443469   22.5701972   23.64489413  24.77076356
  25.95024211  27.18588243  28.48035868  29.8364724   31.2571585
  32.7454916

# Indexing
array[start:stop: step]

In [23]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Pull out second element of third row
print(a[2][1])
print('==========')
# Pull out first two rows and columns
print(a[:2,:2])
print('==========')
# Pull all elements of the third row
print(a[2,:])

8
[[1 2]
 [4 5]]
[7 8 9]


# Integer array indexing

In [24]:
# An example of integer array indexing
a=np.array([[1,2],[3,4],[5,6]])

print(a[[0,1,2],[0,1,0]])
print('==========')

print(np.array([a[0,0],a[1,1],a[2,0]]))
print('==========')

print(a[[0,0],[1,1]])
print('==========')

print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


# Boolean indexing
A boolean index array is of the same shape as the array-to-be-filtered and it contains only True and False values. You can filter those you want using the concept of masking. For ex: If for some array a and boolean condition condition = a > 2, a[condition] will result in an array that contains only the numbers in array a that is greater than 2.

In [25]:
a = np.array([[4,7,1],[2,5,7],[7,1,1]])

# Boolean condition for values greater than 3
mask = a > 3
print(mask)

# Masking for the above boolean condition in the array
print(a[mask])

[[ True  True False]
 [False  True  True]
 [ True False False]]
[4 7 5 7 7]


# What is vectorization?
Vectorization is the ability of NumPy by which we can perform operations on entire arrays rather than on a single element.

In [26]:
a = np.array([1,2,3,4,5,6,7])
print(a[a > 2])

[3 4 5 6 7]


# Vectorized operations
Addition

Subtraction

Multiplication

Division

# Addition

Two ways to go about it, using either + or np.add()

In [27]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])

# element wise addition
print(a+b)
print('==========')
print(np.add(a,b))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]


# Subtraction
Two ways, - or np.subtract()

In [28]:
print(a-b)
print('==========')
print(np.subtract(a,b))

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


# Multiplication
Two ways, * or np.multiply()

In [29]:
print(a*b)
print('==========')
print(np.multiply(a,b))

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


# Division
Two ways, / or np.divide()

In [30]:
print(a/b)
print('==========')
print(np.divide(a,b))

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


# Square root transform
Use np.sqrt()

In [31]:
a = np.array([[1,4,9],[16,25,36]])
print(np.sqrt(a))

[[1. 2. 3.]
 [4. 5. 6.]]


# Log transform
Use np.log()

In [32]:
a = np.array([[1,4,9],[16,25,36]])
print(np.log(a))

[[0.         1.38629436 2.19722458]
 [2.77258872 3.21887582 3.58351894]]


# Aggregrate operations
Aggregration operations are those where we perform some operation on the entire array. Some commonly used aggregrate operations are listed below:

Command	- Description

a.sum() -Array-wise sum

a.min() - Array-wise minimum value

a.max(axis=0) - Maximum value of an array row

a.cumsum(axis=1) - Cumulative sum of the elements

a.mean() - Mean

np.median(a) - Median

np.corrcoef(a) - Correlation coefficient

np.std(a) - Standard deviation

# Array comparison
Use the command np.array_equal() for array comparison.

In [36]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(np.array_equal(a,b))

True


# Understanding Axes notation
In NumPy, an axis refers to a single dimension of a multidimensional array. By changing axis you can compute across dimensions, whereas not specifying axis will result in computation over the entire array.

In [38]:
a = np.array([[1,4,9],[16,25,36]])

# computes sum over columns
print(a.sum(axis=0))
print('==========')

# computes sum over rows
print(a.sum(axis=1))
print('==========')

# computes total sum
print(a.sum())

[17 29 45]
[14 77]
91
